### PR TITLE
Update to gnome-team icons

### PR DESCRIPTION
**Pull request by joekir**
Added icons and tested on device.
Haven't checked on bizarre form factors yet.

freeotp/freeotp-android#110

### CODE REVIEW

**Comment by joekir** [comment]
FYI that Travis fail isn't coming from these commits (there are no real code changes here, just icon references) it's some other issue we need to look at.

**Comment by npmccallum** [comment]
The build issue seems to be related to this: https://docs.travis-ci.com/user/languages/android/#Dealing-with-Licenses

I have tried this: 116ffc9c8630f4bcbd5bf0cc7e5a8f747e6b3d79

**Comment by npmccallum** [comment]
After I merged this, I realized that this means we don't get a colored background on the tokens. Can you add this?

**Comment by joekir** [comment]
Comparing to the old icon, I don't think there was a background it was the image itself that was a square instead of transparent like the new one, I can try colour match that, or did you mean the whole token slab should be a blue colour?

Perhaps you can screencap what you mean just so I'm sure we're talking about the same issue.

I also noticed that the manual add icon is missing on the form factor I'm testing on and will need to verify if this change introduced that regression, was there another commit to remove that feature?

**Comment by npmccallum** [comment]
I just want some default background color (it doesn't have to be blue) for images with transparent backgrounds. Basically, if the image doesn't take up the full ImageView, there should be a color which fills the view. Basically, the ImageView should always visibly be a square (even if the image inside it isn't).

The manual add icon was removed intentionally here: 7851b8e4742b47063376ac5f01543b0d1fc0d42c

**Comment by joekir** [comment]
Ok, I'll try take a look at that later today. Personally I quite like it looking clean and simple, but I'll try find a colour in the scheme that works for what you're after :D 

WRT the manual add what were the motives around that? Should we potentially hide-by-default via a settings flag instead of removing in case there were some members of the community that used that feature?

**Comment by npmccallum** [comment]
I'd prefer to use this instead:
https://freeotp.github.io/qrcode.html

**Comment by joekir** [comment]
Yeah, I forgot about that, perhaps we could make the link to that more obvious in the app's info view, as currently you can click to go to the freeotp landing page then the QR code generator, but it's arguably non-obvious.

**Comment by npmccallum** [comment]
Agreed.

**Comment by joekir** [comment]
Please see PR https://github.com/freeotp/freeotp-android/pull/156 for the colour updates as requested.

**Pull request merged**
