### PR TITLE
use google repo, stable gradle tools, use Travis CI, disableBackup

### PR DESCRIPTION
**Pull request by bufferoverflow**
allowBackup is a security risk.

@npmccallum just let me know if you like individual pull requests.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
Travis CI: https://travis-ci.org/siemens/freeotp-android/builds/273281750

**Comment by bufferoverflow** [comment]
Thanks for the review @jan-kiszka , just added some more details to the commit message. I currently do not know where to describe that limitation as the documentation is just an about box and a web site.

**Comment by npmccallum** [comment]
Please do separate pull requests. Also, the permissions you remove are in fact needed for the token image provisioning feature.

**Comment by bufferoverflow** [comment]
@npmccallum thanks for the feedback, I made these pull requests:
* https://github.com/freeotp/freeotp-android/pull/127
* https://github.com/freeotp/freeotp-android/pull/128
* https://github.com/freeotp/freeotp-android/pull/129
* https://github.com/freeotp/freeotp-android/pull/130

One question about the permission, does the token image provisioning feature need `INTERNET` as well?

**Comment by npmccallum** [comment]
Yes. It downloads the image from a URL, usually http(s).

**Comment by npmccallum** [comment]
I'm closing this PR in lieu of the broken out pull requests.

**Pull request closed without merging**
