### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by jackaw**
Add translated strings

### CODE REVIEW

**Comment by justin-stephenson** [comment]
Build fails with:

~~~
ERROR:/home/runner/work/freeotp-android/freeotp-android/mobile/src/main/res/values-pt-rPT/strings.xml:12:5: Resource and asset merger: The end-tag for element type "string" must end with a '>' delimiter.

    org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 5; The end-tag for element type "string" must end with a '>' delimiter.
    	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
    	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
> Task :mobile:mergeDebugResources FAILED
~~~

**Review by jackaw — COMMENTED** [review]
add missing ">" on line 11,

**Comment by justin-stephenson** [comment]
Re-running CI

**Comment by justin-stephenson** [comment]
Thank you for the PR.

**Pull request merged**
