### PR TITLE
Upgrade some dependencies

### PR DESCRIPTION
**Pull request by joggee-fr**
A small (first) step to update the dependencies of the project.

### CODE REVIEW

**Comment by justin-stephenson** [comment]
Thank you for the PR @joggee-fr 

It looks like `mockito` needs to be updated as well 

```
Starting 210 tests on test(AVD) - 10
Test run failed to complete. Expected 210 tests, received 206. Time: 158.622
There was 1 failure:
1) org.fedorahosted.freeotp.TokenAdapterTest
org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: class android.content.Context.
```

https://github.com/freeotp/freeotp-android/actions/runs/9714722536/job/26814449772?pr=403

**Comment by joggee-fr** [comment]
Thanks @justin-stephenson. I will check this issue but I need to understand a bit more how these Mockito tests run first.

**Comment by joggee-fr** [comment]
@justin-stephenson, my last commit should fix the issue observed with token adapter tests.
I may open later a new PR to really upgrade the test dependencies as it should not impact the distributed application.

**Comment by justin-stephenson** [comment]
Thank you very much @joggee-fr PR looks good to me!

**Pull request merged**
