### PR TITLE
Widgets

### PR DESCRIPTION
**Pull request by meme**
Continuation off of #100 (due to inactivity)

### CODE REVIEW

**Comment by meme** [comment]
Also: I was not sure what the reviewer meant in https://github.com/freeotp/freeotp-android/pull/100#discussion_r163487361

**Comment by olivierperez** [comment]
Did you looked at the comment I made on the #100 ?

**Comment by meme** [comment]
Awesome! I'll look into this, thanks. Just curious: are the tests broken or something? I'll try to run the tests locally and see if I get the same NullPointerExceptions that Travis seems to be getting.

**Comment by olivierperez** [comment]
Can you also remove the `.idea` folder of the PR, it should not be committed.

You may add it to `.gitignore`.

**Comment by meme** [comment]
Alright, so, it seems that the unit tests are failing for me locally as well, I feel like we might want to handle that in a separate pull request or possibly master? I could just pull them back in here.

**Comment by meme** [comment]
As well, I'll look into the `drawableLeft` as soon as I can, I'll try to find the time.

**Pull request closed without merging**
