### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by WebSnke**

### CODE REVIEW

**Comment by sandakersmann** [comment]
You should change these links: https://support.google.com/android/answer/2819582?hl=en

Change to this: https://support.google.com/android/answer/2819582?hl=de

**Comment by WebSnke** [comment]
> You should change these links: [support.google.com/android/answer/2819582?hl=en](https://support.google.com/android/answer/2819582?hl=en)
> 
> Change to this: [support.google.com/android/answer/2819582?hl=de](https://support.google.com/android/answer/2819582?hl=de)

Done.

**Comment by WebSnke** [comment]
> Thank you @WebSnke could you please squash into a single commit?

How do I do that?

**Comment by justin-stephenson** [comment]
https://www.git-tower.com/learn/git/faq/git-squash

**Comment by WebSnke** [comment]
> Thank you @WebSnke could you please squash into a single commit?

Done.

**Comment by WebSnke** [comment]
@justin-stephenson
When are you going to publish the new version on the PlayStore?

**Comment by justin-stephenson** [comment]
@WebSnke I'll try to publish a new release in the new few weeks

**Pull request merged**
