### PR TITLE
Added "Enable Clipboard" feature

### PR DESCRIPTION
**Pull request by joekir**
- Added Preferences menu and fragment layout
- Clipboard choice is persisted by default
- Gated the auto-copy/paste on select using this setting
- SharedPreferences is `MODE_PRIVATE` by default. This mitigates tamper here
- There may still be some layout/theming/phrasing choices to be made later
- Manually verified, but with UI changes I think we should manually test more extensively

Fixes freeotp/freeotp-android#63

### CODE REVIEW

**Comment by simao** [comment]
This would be very nice! Thanks

**Comment by ehuggett** [comment]
I would suggest #66 makes this a critical issue, but the default value should be changed to false.

**Comment by npmccallum** [comment]
@joekir I have bluetooth sharing almost working (I haven't pushed the patch yet). This feature is implemented via a "share" menu. In this patch set we disable clipboard by default and move it to the share target. So basically, you click "share" on a token and you get a list of places you can share the code:
 * Clipboard
 * Nearby Bluetooth Devices
 * Et cetera...

This accomplishes the same thing as your patch but in a different, and I think cleaner, way. For this reason, I'm closing this PR. Look for this feature to land shortly.

**Comment by joekir** [comment]
Yeah I think I recall discussing this previously, sounds good to me.

**Pull request closed without merging**
